db:
  url: jdbc:mysql://localhost:3306/shopcart
  username: shopcart
  password: shopcart
  table: shopcart
  connections: 2   # Максимальное количество одновременных подключений
  column:
    id: id
    type: type
    item: item
    player: player
    amount: amount
    extra: extra
    server: server

  multiserver:
    enabled: false

    # То, что написано в колонке server
    server: 1