name: ShoppingCartReloaded
version: AUTOVERSION
description: Plugin for giving items from web-shops
author: limito

main: me.limito.bukkit.shopcart.PluginPreloader
softdepend: [PowerNBT, PermissionsEx, Vault, WorldGuard]

commands:
  cart:
